<?xml version="1.0" encoding="utf-8"?><Database Name="king21_database" Class="SMSDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=king21_database;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SMSDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SMS_eMoney" Member="SMS_eMoneys">
    <Type Name="SMS_eMoney">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_ActivationCode" Member="SMS_ActivationCodes">
    <Type Name="SMS_ActivationCode">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PINCode" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_Dummy" Member="SMS_Dummies">
    <Type Name="SMS_Dummy">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Reference_No" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Group_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Account_No" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Family_Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Sponsor_ID" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="CP_Number" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Section_A" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Section_B" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DateReg" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_Members" Member="SMS_Members">
    <Type Name="SMS_Member">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReferenceNo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Group_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Account_Number" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Family_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sponsor_ID" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="CP_Number" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Section_A" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Section_B" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Pin_Code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DateReg" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="monthOf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="yearOf" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_QueuedBox" Member="SMS_QueuedBoxes">
    <Type Name="SMS_QueuedBox">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Network" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_Accessibilities" Member="SMS_Accessibilities">
    <Type Name="SMS_Accessibility">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="access" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_User" Member="SMS_Users">
    <Type Name="SMS_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="admin" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="added_by" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_ReceivedMsg" Member="SMS_ReceivedMsgs">
    <Type Name="SMS_ReceivedMsg">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateReceived" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MonthOf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YearOf" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_Inbox" Member="SMS_Inboxes">
    <Type Name="SMS_Inbox">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateReceived" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MonthOf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YearOf" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_WeatherForecast" Member="SMS_WeatherForecasts">
    <Type Name="SMS_WeatherForecast">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="weather_code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="selected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_Reply" Member="SMS_Replies">
    <Type Name="SMS_Reply">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tagged_ID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_TransferFundReport" Member="SMS_TransferFundReports">
    <Type Name="SMS_TransferFundReport">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReferenceNo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Receiver" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DateTransfered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_SentItems" Member="SMS_SentItems">
    <Type Name="SMS_SentItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MonthOf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YearOf" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_Bayanihan" Member="SMS_Bayanihans">
    <Type Name="SMS_Bayanihan">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="refNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bayanihan_ref" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="donator" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="combination" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="donation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="date_danated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_BayanihanSum" Member="SMS_BayanihanSums">
    <Type Name="SMS_BayanihanSum">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bayanihan_ref" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="played" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="combination_no_win" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="total_win" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_win_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="open_started" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="closing_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_DevelopersAccount" Member="SMS_DevelopersAccounts">
    <Type Name="SMS_DevelopersAccount">
      <Column Name="dev_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="access_token" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="secret_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_VirtualMoney" Member="SMS_VirtualMoneys">
    <Type Name="SMS_VirtualMoney">
      <Column Name="vmid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="refno" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>